# Generated by Django 5.2.11 on 2026-09-11 05:27

import django.db.models.deletion
import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=25)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='unit_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('KG', 'Kg'), ('LITER', 'Liter'), ('PIECE', 'Piece')], max_length=10)),
                ('unit_code', models.IntegerField(default=testapp.models.generate_unit_code)),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=25)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('item_code', models.IntegerField(default=testapp.models.generate_item_code)),
                ('rate', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=25)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.brand_mstr')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.unit_mstr')),
            ],
        ),
    ]
