# Generated by Django 5.2.11 on 2026-09-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_mstr',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
