# Generated by Django 5.2.11 on 2026-09-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_item_mstr_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_mstr',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Liter', 'Liter'), ('Piece', 'Piece')], max_length=10),
        ),
    ]
