# Generated by Django 5.2.11 on 2026-09-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_unit_mstr_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_mstr',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
