# Generated by Django 5.2.11 on 2026-09-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_item_mstr_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_mstr',
            name='total',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_mstr',
            name='rate',
            field=models.FloatField(),
        ),
    ]
