# Generated by Django 5.2.11 on 2026-09-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_item_mstr_total_alter_item_mstr_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_mstr',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item_mstr',
            name='total',
        ),
    ]
