# Generated by Django 5.2.11 on 2026-09-14 09:40

import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_item_mstr_quantity_remove_item_mstr_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_purchase_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField(default=testapp.models.generate_invoice_no)),
                ('invoice_date', models.DateTimeField()),
                ('total_amount', models.FloatField()),
                ('name', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('igst', models.IntegerField(default={5: 5, 12: 12, 15: 15})),
                ('cgst', models.IntegerField(default={5: 5, 12: 12, 15: 15})),
            ],
        ),
    ]
