# Generated by Django 5.2.11 on 2026-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_tbl_purchase_mstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_purchase_mstr',
            name='cgst',
            field=models.IntegerField(choices=[(12, 12), (5, 5), (15, 15)], default=5),
        ),
    ]
