# Generated by Django 5.2.11 on 2026-09-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_tbl_purchase_mstr_cgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_purchase_mstr',
            name='igst',
            field=models.IntegerField(choices=[(12, 12), (5, 5), (15, 15)], default=12),
        ),
    ]
