# Generated by Django 5.2.11 on 2026-09-14 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_tbl_purchase_mstr_igst'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_purchase_mstr',
            name='contact_no',
            field=models.CharField(default=100, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_purchase_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('igst', models.IntegerField(choices=[(12, 12), (5, 5), (15, 15)], default=12)),
                ('cgst', models.IntegerField(choices=[(12, 12), (5, 5), (15, 15)], default=5)),
                ('amount', models.FloatField()),
                ('rate', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.item_mstr')),
                ('purcahse_mstr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tbl_purchase_mstr')),
            ],
        ),
    ]
