# Generated by Django 5.2.11 on 2026-09-15 09:11

import django.core.validators
import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_tbl_purchase_mstr_contact_no_tbl_purchase_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sales_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField(default=testapp.models.generate_invoice_no)),
                ('invoice_date', models.DateTimeField()),
                ('total_amount', models.FloatField()),
                ('name', models.CharField(max_length=25)),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('igst', models.IntegerField(choices=[(12, 12), (5, 5), (15, 15)], default=12)),
                ('cgst', models.IntegerField(choices=[(12, 12), (5, 5), (15, 15)], default=5)),
            ],
        ),
    ]
