# Generated by Django 5.2.11 on 2026-09-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_tbl_sales_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_sales_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('igst', models.IntegerField(choices=[(12, 12), (5, 5), (15, 15)], default=12)),
                ('cgst', models.IntegerField(choices=[(12, 12), (5, 5), (15, 15)], default=5)),
                ('amount', models.FloatField()),
                ('rate', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.item_mstr')),
                ('sales_mstr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tbl_sales_master')),
            ],
        ),
    ]
