# Generated by Django 5.2.11 on 2026-09-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_purchase_report_sales_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_mstr',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
