# Generated by Django 5.2.11 on 2026-09-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_item_mstr_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_sales_master',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
