# Generated by Django 5.2.11 on 2026-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_tbl_sales_master_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_purchase_mstr',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
