# Generated by Django 5.2.11 on 2026-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_alter_tbl_purchase_mstr_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_sales_details',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='table_sales_details',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='tbl_purchase_details',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='tbl_purchase_details',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='tbl_purchase_mstr',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='tbl_purchase_mstr',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='tbl_sales_master',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='tbl_sales_master',
            name='igst',
        ),
        migrations.AddField(
            model_name='table_sales_details',
            name='gst',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='tbl_purchase_details',
            name='gst',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='tbl_purchase_mstr',
            name='gst',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='tbl_sales_master',
            name='gst',
            field=models.FloatField(default=18),
        ),
    ]
