# Generated by Django 5.2.11 on 2026-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_remove_table_sales_details_cgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_sales_details',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='table_sales_details',
            name='igst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_purchase_details',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_purchase_details',
            name='igst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_purchase_mstr',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_purchase_mstr',
            name='igst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_sales_master',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_sales_master',
            name='igst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='table_sales_details',
            name='gst',
            field=models.FloatField(choices=[(12, '12%'), (15, '15%'), (18, '18%')], default=18),
        ),
        migrations.AlterField(
            model_name='tbl_purchase_details',
            name='gst',
            field=models.FloatField(choices=[(12, '12%'), (15, '15%'), (18, '18%')], default=18),
        ),
        migrations.AlterField(
            model_name='tbl_purchase_mstr',
            name='gst',
            field=models.FloatField(choices=[(12, '12%'), (15, '15%'), (18, '18%')], default=18),
        ),
        migrations.AlterField(
            model_name='tbl_sales_master',
            name='gst',
            field=models.FloatField(choices=[(12, '12%'), (15, '15%'), (18, '18%')], default=18),
        ),
    ]
